### ISSUE TITLE
Remove unrelated slides

### ISSUE THREAD

**Issue by haf** [fsprojects/FsReveal#110]
...from master.

**Comment by theimowski** [comment]
ping @forki - it seems 958c775 should be the commit on master branch, and all newer commits are part of your custom presentation?

**Comment by vbfox** [comment]
Same as #117 Now fixed

**Comment by forki** [comment]
Thanks. Hugs

Julien Roncaglia <notifications@github.com> schrieb am Mo., 29. Okt. 2018,
17:45:
