### ISSUE TITLE
What is in the Sample folder?

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/FsReveal#117]
I just downloaded fresh copy of FsReveal and I'm not sure what is the purpose of the Fable/Elmish project in the `Sample` project. 

This seems to be from a commit by @forki (https://github.com/fsprojects/FsReveal/commit/5d4833f8a5b74bec3f2c3538af2476e7e336f8c4), but there is no PR for it and also I do not see much about this in the docs.

Can someone explain what this does?

**Comment by forki** [comment]
Can't remember tbh. ;-(

Tomas Petricek <notifications@github.com> schrieb am Di., 25. Sep. 2018,
06:53:

**Comment by vbfox** [comment]
Seem like everything after 73cb488a3b2beaf3e700d5d4537dc9ba16396203 shouldn't be there...

```bash
git reset --hard 73cb488a3b2beaf3e700d5d4537dc9ba16396203
git cherry-pick cd6407373295c2c5711e501496e9de61062296ac
git push -f
```

**Comment by forki** [comment]
sorry took me a while. but done.

**Comment by vbfox** [comment]
👍 you might want to cherry-pick the paket bootstrapper update too :)

**Comment by forki** [comment]
I think I did

**Comment by vbfox** [comment]
@forki I think there still is a problem with the master branch, the commits changed but the ones with the presentation are still there, It seem that only the bootstrapper commit is missing from the previous state

**Comment by forki** [comment]
I think I followed the commands that you listed above.

Julien Roncaglia <notifications@github.com> schrieb am Mo., 29. Okt. 2018,
14:12:

**Comment by vbfox** [comment]
Weird, I might have serious git understanding problems

The previous state was (Taken from a fork that still has it) :

![image](https://user-images.githubusercontent.com/131878/47662309-f49a4e80-db9a-11e8-90c1-d60ad478eb98.png)

New state :

![image](https://user-images.githubusercontent.com/131878/47662355-07ad1e80-db9b-11e8-9eae-6a197158359c.png)

With the commands it should have resulted in `73cb488a3b2beaf3e700d5d4537dc9ba16396203` being the second to last commit and a new commit derived from `cd6407373295c2c5711e501496e9de61062296ac` the last one :

From my fork (where I ran the 3 commands and continued to commit after) :

![image](https://user-images.githubusercontent.com/131878/47663105-83f43180-db9c-11e8-81a1-78366708cf11.png)

So I don't know what happened here, normally re-running the commands (on a PC that has seen `cd6407373295c2c5711e501496e9de61062296ac`) should give the correct state.

If needed I can also do the change (given temporary commit access) or do a reverting-PR (It will keep the current history so it's a little more messy but I can do it via PR)

**Comment by vbfox** [comment]
Done

![image](https://user-images.githubusercontent.com/131878/47665629-d08e3b80-dba1-11e8-8268-76e6c4a62027.png)
