### ISSUE TITLE
FsReveal 0.0.5 fails to generate slides for .fsx files

### ISSUE THREAD

**Issue by TonyAbell** [fsprojects/FsReveal#21]
I have tried from the master branch and 0.0.5 and I still get errors on fsx files

**Comment by JacobDanton** [comment]
Is there any update on this item? I am still seeing the same issue.

**Comment by tpetricek** [comment]
It did not work for me. The PR #39 should fix this (I was getting the same error message as @jwood803)

**Comment by ImaginaryDevelopment** [comment]
When I try to run against an .fsx file no errors occur, but the browser says no data received. as reflected in my branch 
https://github.com/ImaginaryDevelopment/FsReveal/tree/bustedfsx
