### ISSUE TITLE
limited source tracking

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FsReveal#30]
There is an unfortunate recursivity to the namespaces of this project, which is not represented under Git source control. 

Among the nuget packages is "FsReveal", which is not this project, but appears to be some version of reveal.js together with an FsReveal.dll (where is the source for this?) and F#.Formatting, all packaged up. 

There are multiple levels of interest in FsReveal.

1) A quick way to clone a skeleton slide presentation, with limited capability of changing the default presentation parameters (and also track those changes in Git). FsProjects/FsReveal meets this need.

2) Tweaking the presentation parameters. This means changing css and javascript. Since this is delivered through a nuget package, it is not under source control and there is no way to track local changes back to the community project.

3) Changes to the FsReveal executable. Whatever witchcraft is going on here is opaque.

I'm not sure what is the best way to represent these different needs. Minimally I would like to track my changes to reveal.css/reveal.min.css and reveal.js/reveal.min.js back to the community project. Perhaps taking these files out of the nuget package, putting them in the "display only" github project, and altering build.fsx to copy them into the proper place in the file system. (And on a side issue, can Fake launch a minifier, so the reveal.min.* files are not required in the distribution?)

I'm sure opening the FsReveal executable source to community involvement would result in some good contributions. 

I have no suggestions for names, but only one of these configurations should be named "FsReveal".

**Comment by kimsk** [comment]
Sorry for the confusion. The `develop` branch is used to be the `master` branch, but we think it'd be better to have the code to generate slide in `master` instead.

For the declaration section, I think @forki means the `properties` section at the beginning of `fsx` or `md` files like [theme](https://github.com/fsprojects/FsReveal/blob/develop/src/presentations/FsReveal.fsx#L5) which is then replaced in generated file [here](https://github.com/fsprojects/FsReveal/blob/develop/src/FsReveal/template.html#L57). So you could create a new property for the page size in the template.
