### ISSUE TITLE
Simpler way of defining speaker notes in markdown

### ISSUE THREAD

**Issue by artur-s** [fsprojects/FsReveal#32]
Currently, to add speaker notes using markdown, the `<aside>` HTML tag decorated with `notes` class has to be used. For example:
```
<aside class="notes">Oh hey, these are some notes.</aside>
```
Defining speaker nodes in a more concise way would be useful.

For example:
`/// Oh hey, these are some notes.`
Or markdown-compliant way, where the note is not included in HTML view ([based on SO question](http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax)):
`[//]: # (Oh hey, these are some notes.)`

**Comment by forki** [comment]
@troykershaw @kimsk what do you think?

**Comment by forki** [comment]
I think triple slashes will be used for F# XML comments. 
How about:

' Oh hey, these are some notes.
' And some more

**Comment by artur-s** [comment]
I like the single quote. It is clear and not common as a first character in a line.

**Comment by forki** [comment]
please take a look at https://github.com/fsprojects/FsReveal/pull/48

**Comment by artur-s** [comment]
@forki, Currently only the first speaker note line appears on the slide notes. It looks like only one `<aside>` element is supported.
