### ISSUE TITLE
Latest FsReveal does not appear to support ---

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FsReveal#33]
I was trying to add a few vertical slides as asides and found that FsReveal blew up on them. Is the `---` no longer supported?

**Comment by forki** [comment]
it's fixed. Please update FsReveal to latest

**Comment by panesofglass** [comment]
I haven't tried yet. I'll pull soon and try again. Thanks!

**Comment by panesofglass** [comment]
Tried it, and I can't retrieve FsReveal from NuGet at all right now. I'll create a new ticket.
