### ISSUE TITLE
Can't pull FsReveal from NuGet

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FsReveal#34]
I tried pulling 0.2.0 and 0.2.1 from NuGet, and the install fails while trying to resolve FSharp.Formatting >= 2.5.0.

@tpetricek, is this a known issue with FSharp.Formatting, by chance? When I tried adding FSharp.Formatting directly, I received a similar issue that FSharp.Compiler.Service >= 0.0.81 could not be resolved.

**Comment by forki** [comment]
what is your dependencies file?

**Comment by panesofglass** [comment]
I ran it from the command line yesterday.

**Comment by forki** [comment]
I fixed some things today. Maybe it's gone
