### ISSUE TITLE
Creating Github Pages

### ISSUE THREAD

**Issue by kijanawoodard** [fsprojects/FsReveal#37]
First up. Thanks for FSReveal. 
I did my first talk using it last night and everything went perfectly.
http://kijanawoodard.github.io/Talk-Missing-Model-Mysteries/#/

As you see, I was able to get my slides to gh-pages. I followed the instructions, but was surprised to see errors. Seeing what the build script was trying to clone, it was obvious that it was trying to pull the wrong repo. I opened the build fsx and found the things to headed by searching for ReleaseSlides and following my nose.

It's a bit clunky for new users.
The easiest "fix" would be to update the docs.
Perhaps it would be possible to pick up the values from the git repo.

Thoughts?

**Comment by forki** [comment]
could you please help to update the docs? Pull requests with clarifications are very welcome.

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/6466615/40e349bc-c1c9-11e4-98f3-054daa2769fe.png)

would this help?

**Comment by kijanawoodard** [comment]
I added https://github.com/fsprojects/FsReveal/compare/develop...kijanawoodard:patch-1

**Comment by forki** [comment]
merged ;-)

**Comment by kijanawoodard** [comment]
whoa. fast.

was figuring out how to properly attach the patch to the issue. ;-)
