### ISSUE TITLE
Ability to patch dependencies

### ISSUE THREAD

**Issue by kfuglsang** [fsprojects/FsReveal#43]
It would be cool to be able to patch dependencies to speed up the process of adding new features into FsReveal.

Specifically, one use case is adding syntax highlight for a new language. This will be an upgrade of the highlight.js library that reveal.js uses for syntax highlight.

The ability to replace the highlight.js project in the build process would allow us to upgrade before reveal.js releases a new version.

**Comment by forki** [comment]
easiest way to do this is to point to a different fork (your fork) see -https://github.com/fsprojects/FsReveal/blob/develop/paket.dependencies#L10

**Comment by kfuglsang** [comment]
Ah cool. That will solve the issue.
