### ISSUE TITLE
Ability to add custom stylesheet into build

### ISSUE THREAD

**Issue by kfuglsang** [fsprojects/FsReveal#44]
It would be cool to have the ability to include a custom stylesheet in the build process.

**Comment by forki** [comment]
like a  custom paket style cheat? or like your own?

**Comment by kfuglsang** [comment]
A cascading style sheet.

Now that I'm thinking of it, it might be very simple to do. Will try to hack something right now.

**Comment by forki** [comment]
woah. I meant a CSS which is FsReveal specific or one that is specific to your presentation?

**Comment by kfuglsang** [comment]
Specific to my presentation.

**Comment by forki** [comment]
ok. then we should do the following:

* in develop branch:
    * modify template to reference a custom css
    * add a bit of docs about it
* in master branch
    * add a default custom style cheat
    * modify the build to copy that thing to the output

**Comment by kfuglsang** [comment]
Exactly what I'm trying to do right now :+1: 

Getting build error in the develop branch though... `Could not load file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

**Comment by forki** [comment]
looks like your missing MSBuild 12 which should be part of .NET 4.5.x I think.

**Comment by kfuglsang** [comment]
I'm on Windows 10 but I just checked all the `Microsoft.Build.Framework.dll` files in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\` and they are all version 4.x

Odd.
