### ISSUE TITLE
Extract the KeepAlive functionality?

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/FsReveal#57]
Would it make sense to extract the "keep alive" functionality from FsReveal, so that it can be easily used in other projects? I just need exactly the same thing in FsLab Journal...

@forki Do you think FAKE could somehow handle this? (Like, create a target that runs other target whenever a contents of a directory changes?)

**Comment by tpetricek** [comment]
Actually, I'm stealing the code to run the server too. So perhaps there is even larger reusable component here (could be just an FS file that could be referenced via Paket...)

**Comment by forki** [comment]
done. we have http://fsharp.github.io/FAKE/watch.html
