### ISSUE TITLE
Example project links are broken

### ISSUE THREAD

**Issue by brodyberg** [fsprojects/FsReveal#59]
http://fsreveal.azurewebsites.net/index-md.html
http://fsreveal.azurewebsites.net/

Appear to be down right now. 

They both show: 

Error 403 - This site is stopped.

The web site you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the Administrator of this web site, please visit the Azure Portal to check why the site is stopped.

**Comment by forki** [comment]
where did you find the links?

**Comment by brodyberg** [comment]
Sorry - under Examples here: http://fsprojects.github.io/FsReveal/

**Comment by kimsk** [comment]
I update the links in our documentation now. Sorry for the issue.

**Comment by brodyberg** [comment]
Thanks!
