### ISSUE TITLE
Install of 0.7.2 nuget package fails

### ISSUE THREAD

**Issue by brodyberg** [fsprojects/FsReveal#60]
Trying to install 0.7.2 with VS 2015 I see an error about what appears to be an invalid nupkg in FsFormatting. 

My version of VS: 

Microsoft Visual Studio Ultimate 2015 Preview
Version 14.0.22310.1 DP
Microsoft .NET Framework
Version 4.6.00042

Installed Version: Ultimate

Screenshot of the actual error: 

![fsreveal_install_fail1](https://cloud.githubusercontent.com/assets/151955/6923934/c036e612-d789-11e4-9acc-2e73b97d6a93.PNG)

**Comment by forki** [comment]
I assume this is a bug in Nuget

**Comment by brodyberg** [comment]
Probably, I don't have time to look right now though.

**Comment by forki** [comment]
also note that fsreveal doesn't really work like that. 
normally you would clone the master branch and run the FAKE script. that will use paket to download the packages.

**Comment by brodyberg** [comment]
I can do that, but that's not ideal for beginners.

**Comment by forki** [comment]
That's the only way it works.
You need the build.cmd to do it's thing. 
The nuget package is basically useless atm.

**Comment by maartenba** [comment]
Please file an issue on www.github.com/nuget/home with repro steps

**Comment by brodyberg** [comment]
No problem. Great project!

**Comment by brodyberg** [comment]
Thanks

**Comment by forki** [comment]
I will create a new issue and also make it more obvious that you need to
clone or download the current master. The nuget package is only a small
part of the project.

Thanks for the feedback.
