### ISSUE TITLE
Copy subfolders for images

### ISSUE THREAD

**Issue by CumpsD** [fsprojects/FsReveal#61]
Currently this codes copies the images:

```
!! (slidesDir @@ "images/*.*")
|> CopyFiles (outDir @@ "images")
```
Basicly it says: take all files in the direct root of ```images``` and copy them, ignoring subfolders.

I propose to copy the entire images directory:

```CopyDir (outDir @@ "images") (slidesDir @@ "images") (fun f -> true)```

This allows people to either keep using it as it is now, directly in the root. But also allows you to organise your images.

I can send a PR if this proposal makes sense.

**Comment by kimsk** [comment]
I think that sounds good. Thanks!
