### ISSUE TITLE
markdown files don't create tooltips properly.

### ISSUE THREAD

**Issue by nicholas-peterson** [fsprojects/FsReveal#63]
Using a markdown file, typing the line

    let add x y = x + y

Generates a pretty printed output in the reveal presentation, but doesn't create the onmouseover parts of the tags needed to display the tooltips. The div's containing the tooltips seem to exist.

I'm basically just editing the slides/index.md and running build.cmd. Anything else needed to make this work?

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/7027493/098dd656-dd50-11e4-9444-5701f3df0489.png)

mhm. works for me.

**Comment by nicholas-peterson** [comment]
Ahh, I see now through manipulating my markdown file it's from me not prepending [lang=cs] to some segments of C# code. I enjoyed the larger rendering style when I didn't specify and apparently it was trying to evaluate them all as F# and eventually just gave up. Mystery solved.
