### ISSUE TITLE
How should I use the develop and master branches when creating custom styles vs other contributions?

### ISSUE THREAD

**Issue by ryanewtaylor** [fsprojects/FsReveal#65]
I forked FsReveal so that I may add a custom CSS style/theme for my organization. Initially, I was making edits in the master branch to index.md and custom.css. However, I started digging deeper to better understand how FsReveal operated. Doing so I noticed that the FsReveal code is on the develop branch and not in the master branch.

How should I use the two two branches? For instance, if I were to simply add a custom style should I do this in the master branch or the develop branch. If I instead were to contribute back would I branch a feature branch from develop and issue a PR?

Is there a contributing page that answers these questions?

**Comment by kimsk** [comment]
Basically, the `master` branch is for creating your `FsReveal` presentation, so it contains only sample files. And you should put the custom style there.

The `FsReveal` code in `develop` branch is published to NuGet and used by `build.fsx` in the `master` branch. PR should be sent to `develop` branch unless you update the [build.fsx](https://github.com/fsprojects/FsReveal/blob/master/build.fsx). 

I don't think we have contribution page right now, but it'd be good idea to have one.

**Comment by ryanewtaylor** [comment]
Thanks for the clarification!
