### ISSUE TITLE
Missing PowerShell syntax highlighting

### ISSUE THREAD

**Issue by brianary** [fsprojects/FsReveal#66]
Providing lang=PowerShell, posh, ps, &c doesn't syntax highlight PowerShell code.

**Comment by forki** [comment]
That's something for the upstream project. Try to open an issue for highlight.js

**Comment by brianary** [comment]
It's been added in version 8.3 of highlight.js; it looks like FsReveal uses 8.2.

**Comment by fbehrens** [comment]
highlight.js is now version `v8.9.1`
I have tested that `[lang=powershell]` is working.
Can be closed
