### ISSUE TITLE
SQL code renders single quotes as &#39;

### ISSUE THREAD

**Issue by brianary** [fsprojects/FsReveal#67]
Providing code like:

    [lang=sql]
    select * from pubs where author = 'King';

Renders as:

    select * from pubs where author = &#39;King&#39;;

(but it does highlight correctly)

**Comment by forki** [comment]
this is already fixed in latest FSharp.Formatting, but we need https://github.com/fsprojects/Paket/issues/812 to push a new package.

**Comment by forki** [comment]
fixed
