### ISSUE TITLE
Only the first speaker note is shown if multiple notes are separated by empty lines

### ISSUE THREAD

**Issue by john-azariah-cba** [fsprojects/FsReveal#70]
The following set of speaker notes results in only the first one showing:

' This is a note

' This is a second note

Is this by design? It would be good if both were shown in the notes area!

**Comment by forki** [comment]
I assume it's a parsing issue.

**Comment by john-azariah-cba** [comment]
How can I help fix it? :smile:

**Comment by forki** [comment]
If you are really interested in fixing, then checkout the develop branch.
you will find a test project with couple of unit tests. Try to copy one,
make it red and come up with a fix ;-)

If you doesn't get it working I'm happy to help.

**Comment by john-azariah-cba** [comment]
I wrote the failing test - but I'm on my work mac and unable to build the project :(

In SpeakerNotesSpecs.fs

---
19: 
20:' Oh hey, these are some notes.
21: <inserted a blank line here>
22:' And some more
---

That should parse to the same result...

**Comment by forki** [comment]
mhm. what's the issue? why can't you build it?

**Comment by john-azariah-cba** [comment]
don’t have Xamarin on this box :)

From: Steffen Forkmann
Reply-To: fsprojects/FsReveal
Date: Tuesday, 2 June 2015 5:01 pm
To: fsprojects/FsReveal
Cc: John Azariah
Subject: Re: [FsReveal] Only the first speaker note is shown if multiple notes are separated by empty lines (#70)


mhm. what's the issue? why can't you build it?

—
Reply to this email directly or view it on GitHub<https://github.com/fsprojects/FsReveal/issues/70#issuecomment-107832756>.

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by forki** [comment]
you should still be able to run build.sh

**Comment by john-azariah-cba** [comment]
OK – I can do that – but how do I run tests? Let me look for a readme :)

From: Steffen Forkmann
Reply-To: fsprojects/FsReveal
Date: Tuesday, 2 June 2015 5:05 pm
To: fsprojects/FsReveal
Cc: John Azariah
Subject: Re: [FsReveal] Only the first speaker note is shown if multiple notes are separated by empty lines (#70)


you should still be able to run build.sh

—
Reply to this email directly or view it on GitHub<https://github.com/fsprojects/FsReveal/issues/70#issuecomment-107833273>.

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by john-azariah-cba** [comment]
Project "/Users/azariajo/workspace/play/FsReveal/FsReveal.sln" (Rebuild target(s)):

Target ValidateSolutionConfiguration:

Building solution configuration "Release|Any CPU".

Target Rebuild:

/Users/azariajo/workspace/play/FsReveal/src/FsReveal/FsReveal.fsproj: error : /Users/azariajo/workspace/play/FsReveal/src/FsReveal/FsReveal.fsproj: The required attribute "Project" in Import is empty

/Users/azariajo/workspace/play/FsReveal/tests/FsReveal.Tests/FsReveal.Tests.fsproj: error : /Users/azariajo/workspace/play/FsReveal/tests/FsReveal.Tests/FsReveal.Tests.fsproj: The required attribute "Project" in Import is empty

Task "MSBuild" execution -- FAILED

Done building target "Rebuild" in project "/Users/azariajo/workspace/play/FsReveal/FsReveal.sln".-- FAILED

Done building project "/Users/azariajo/workspace/play/FsReveal/FsReveal.sln".-- FAILED


From: Steffen Forkmann
Reply-To: fsprojects/FsReveal
Date: Tuesday, 2 June 2015 5:05 pm
To: fsprojects/FsReveal
Cc: John Azariah
Subject: Re: [FsReveal] Only the first speaker note is shown if multiple notes are separated by empty lines (#70)


you should still be able to run build.sh

—
Reply to this email directly or view it on GitHub<https://github.com/fsprojects/FsReveal/issues/70#issuecomment-107833273>.

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by forki** [comment]
`build.sh RunTests` should build and run all test. https://github.com/fsprojects/FsReveal/blob/develop/build.fsx#L127

but seems you have other issues.

**Comment by john-azariah-cba** [comment]
Yeah – have people run this on mono??

:(

From: Steffen Forkmann
Reply-To: fsprojects/FsReveal
Date: Tuesday, 2 June 2015 5:09 pm
To: fsprojects/FsReveal
Cc: John Azariah
Subject: Re: [FsReveal] Only the first speaker note is shown if multiple notes are separated by empty lines (#70)


build.sh RunTests should build and run all test. https://github.com/fsprojects/FsReveal/blob/develop/build.fsx#L127

but seems you have other issues.

—
Reply to this email directly or view it on GitHub<https://github.com/fsprojects/FsReveal/issues/70#issuecomment-107833945>.

************** IMPORTANT MESSAGE *****************************       
This e-mail message is intended only for the addressee(s) and contains information which may be
confidential. 
If you are not the intended recipient please advise the sender by return email, do not use or
disclose the contents, and delete the message and any attachments from your system. Unless
specifically indicated, this email does not constitute formal advice or commitment by the sender
or the Commonwealth Bank of Australia (ABN 48 123 123 124) or its subsidiaries. 
We can be contacted through our web site: commbank.com.au. 
If you no longer wish to receive commercial electronic messages from us, please reply to this
e-mail by typing Unsubscribe in the subject line. 
**************************************************************

**Comment by forki** [comment]
I just looked at the issue.

why can't you do

    ' This is a note
    ' 
    ' This is a second note

?

**Comment by john-azariah-cba** [comment]
I can!

**Comment by forki** [comment]
yeah. I think it's better to do so. The code is a bit difficult there.
