### ISSUE TITLE
Support PDF export

### ISSUE THREAD

**Issue by ryanewtaylor** [fsprojects/FsReveal#87]
Not sure if this is a bug or an idea but it would be useful to support the PDF export of the slides. This is something that [Reveal.js does](https://github.com/hakimel/reveal.js#pdf-export) and would be a nice addition to FsReveal for those times where you just need a PDF.

**Comment by forki** [comment]
It should actually already work since we create reveal.js solutions. I
remember doing this.

**Comment by ryanewtaylor** [comment]
You're right. This was user error, I needed to add the ?print-pdf string *before* the final forward slash so that my URL looked like `http://localhost:8083/index.html?print-pdf#/`. Further, I had to select Chrome's "Save as PDF" option rather than the Adobe Acrobat printed I had installed.

It worked perfectly after that.
