### ISSUE TITLE
Method 'FSharpChecker.set_ImplicitlyStartBackgroundWork' not found

### ISSUE THREAD

**Issue by panesofglass** [fsprojects/FsReveal#91]
I have been unable to generate slides for my [domain-modeling talk](https://github.com/panesofglass/domain-modeling/tree/feature/latest-fsreveal) with the latest version of FsReveal:

```
Could not generate slides for: /Users/admin/Code/domain-modeling/slides/index.fsx
Method 'FSharpChecker.set_ImplicitlyStartBackgroundWork' not found.
```

Any ideas?

**Comment by forki** [comment]
You mean out of the box or did you get upgrade issues? 

Like @isaac_abraham already said: upgrade experience is not really nice since, you always need to update the build script as well. 

Please try the (super annoying and hopefully only temporary) workaround. Clone this repo again, copy slides.md and pictures over from the old clone. 
Does this work?

**Comment by panesofglass** [comment]
I'm using a `index.fsx`. Is that no longer supported? Are only `*.md` files now supported?

**Comment by forki** [comment]
Nope should be working as well

**Comment by panesofglass** [comment]
Starting over and doing a bit at a time, I got it working. I started this time by updating FAKE. I noticed that FAKE was a major version behind in the previous attempt, which may have had something to do with it. Thanks!

**Comment by forki** [comment]
Something we could do better in the future?

**Comment by panesofglass** [comment]
I don't think so. I just missed the updated FAKE dependency it would seem. That or I tried to update too many dependencies at once.

**Comment by isaacabraham** [comment]
I've worked around this by adding both suave and the build script as Paket dependencies. I then have a small copy task in build.cmd to copy the fsx from paket-files to root folder.
